version: '3.8'

services:

  entregasadomicilio.web.platillos.api:
    #image: ${DOCKER_REGISTRY-}entregasadomiciliowebplatillosapi
    build: 
      context: .
      dockerfile: web_platillos.Dockerfile
    #ports:
     # - 9080:80 

  entregasadomicilio.usuarios.api:
    #image: ${DOCKER_REGISTRY-}entregasadomiciliousuariosapi
    build:
      context: .
      dockerfile: Dockerfile_usuarios.Dockerfile
# para ejecutar: docker-compose up

