version: '3.4'

services:
  entregasadomicilio.web.platillos.api:
    image: ${DOCKER_REGISTRY-}entregasadomiciliowebplatillosapi
    build: 
      context: .
      dockerfile: EntregasADomicilio.Web.Platillos/Dockerfile
    ports:
      - 9080:80
